### PR TITLE
update from the `node-sass` package to the `sass` package

### PR DESCRIPTION
**Pull request by trusktr**
Updates to the new `sass` package. The stable branch works for me now, I can drag actions and the inspector updates while I do so, everything seems look fine. Needs a second set of :eyes:.

### CODE REVIEW

**Comment by alizenguyen** [comment]
I don't see anything wrong with it. But, I would feel more comfortable once Deep gets a chance to look as well since I'm still learning integration with openMCT. Thanks!

**Comment by trusktr** [comment]
No prob. If you don't mind though, it would be great if during review you can test out your features to make sure they all work, at least until I am comfortable enough to the point where I would be able to confidently know a feature broke or not (I didn't know last time: I thought action dragging wasn't implemented yet, oops).

**Comment by alizenguyen** [comment]
Sure! I'm working on finishing the height adjustment buttons for chronicles so I can get a pull request out today. I can switch to your branch and run through the process later tonight or tomorrow morning.

**Comment by trusktr** [comment]
Cool. Thanks! Will be nice when automated tests are in place to check things.

**Review by deeptailor — APPROVED** [review]
Looks good, thanks for the fix! We will have to rely on the built css file for now, until Open MCT fixes the underlying issue.

**Pull request merged**
